// Generated by CoffeeScript 1.9.2

/**
Utility singleton for working with URLs and paths.
@module AP
@submodule utility
@class Url
@static
@private
 */
AP.utility.Url = (function($class) {
  
  var url = $class({
    
    _constructor: function Url() {},
    
    static: {
      parseUrl: function(url) {
        var matches, path;
        path = {
          urlParseRE: /^\s*(((([^:\/#\?]+:)?(?:(\/\/)((?:(([^:@\/#\?]+)(?:\:([^:@\/#\?]+))?)@)?(([^:\/#\?\]\[]+|\[[^\/\]@#?]+\])(?:\:([0-9]+))?))?)?)?((\/?(?:[^\/\?#]+\/+)*)([^\?#]*)))?(\?[^#]+)?)(#.*)?/,
          getLocation: function(url) {
            var hash, uri;
            uri = url ? this.parseUrl(url) : location;
            hash = this.parseUrl(url || location.href).hash;
            hash = hash === '#' ? '' : hash;
            return uri.protocol + '//' + uri.host + uri.pathname + uri.search + hash;
          }
        };
        if ($.type(url) === 'object') {
          return url;
        }
        matches = path.urlParseRE.exec(url || '') || [];
        return {
          href: matches[0] || '',
          hrefNoHash: matches[1] || '',
          hrefNoSearch: matches[2] || '',
          domain: matches[3] || '',
          protocol: matches[4] || '',
          doubleSlash: matches[5] || '',
          authority: matches[6] || '',
          username: matches[8] || '',
          password: matches[9] || '',
          host: matches[10] || '',
          hostname: matches[11] || '',
          port: matches[12] || '',
          pathname: matches[13] || '',
          directory: matches[14] || '',
          filename: matches[15] || '',
          search: matches[16] || '',
          hash: matches[17] || ''
        };
      }
    }
  });
  
  return url;
  
})(AP.utility.createClass);
